// 內部工作台（CaseWorkBoard）的中英字串。從 PV-Link 的 i18n/work.ts 搬入；本機試用模式已拿掉，它的提示字串一併刪除。
export const workZh = {
 'work.title': '個案工作狀態、日期工作台與站內提醒', 'work.note': '僅供 PV 內部作業；工作狀態與工作到期日均與法規個案狀態／法規到期日分開。不寄信、不建立追蹤通報。',
 'work.today': '今日', 'work.week': '本週', 'work.overdue': '逾期', 'work.timezone': '產品工作時區', 'work.timezoneValue': 'Asia/Taipei', 'work.refreshOnly': '僅於開啟／重新整理工作台時更新到期提醒；非背景推播或排程。',
 'work.notifications': '站內提醒', 'work.markRead': '標示為已讀', 'work.read': '已讀', 'work.dueNotice': '有一項內部工作已到期或逾期。', 'work.assignedNotice': '有一項內部工作已分派給您。',
 'work.status': '內部工作狀態', 'work.statusSeparate': '此狀態不會變更法規個案狀態、Day 0 或送件流程。', 'work.status.todo': '待辦', 'work.status.in-progress': '進行中', 'work.status.waiting': '等待中', 'work.status.completed': '已完成', 'work.status.cancelled': '已取消', 'work.cancelReason': '取消原因（必填，最多 500 字）',
 'work.owner': '負責人', 'work.next': '下一步', 'work.due': '內部工作到期日', 'work.items': '補件清單', 'work.addItem': '新增補件項目', 'work.pending': '待取得', 'work.received': '已取得', 'work.cancelled': '已取消', 'work.contacts': '聯絡紀錄', 'work.addContact': '新增聯絡紀錄', 'work.date': '聯絡日期', 'work.method': '聯絡方式', 'work.result': '聯絡結果', 'work.follow': '下次追蹤日期', 'work.phone': '電話', 'work.email': '電子郵件', 'work.visit': '拜訪', 'work.other': '其他', 'work.unassigned': '未分派', 'work.save': '儲存工作', 'work.reload': '重新整理工作台', 'work.loading': '載入中…', 'work.saved': '已儲存',
 'work.unread': '未讀', 'work.unsaved': '未儲存', 'work.itemTitle': '補件項目', 'work.itemStatus': '取得狀態', 'work.auditVersion': '版本', 'work.auditAt': '時間', 'work.auditActor': '操作者', 'work.auditAction': '動作', 'work.action.work_saved': '儲存', 'work.action.work_completed': '標記完成', 'work.action.work_cancelled': '取消工作', 'work.action.work_reopened': '重新開啟',
 'work.error': '無法載入或儲存。請確認連線、PV 權限及 schema；您的編輯尚未儲存。', 'work.conflict': '其他人已修改。您的編輯仍保留，請先複製需要保留的內容，再重新載入最新版後重填。', 'work.invalid': '請檢查狀態轉移、取消原因、日期、長度及負責人。', 'work.audit': '伺服器稽核紀錄', 'work.dirty': '有未儲存編輯，請先儲存或放棄編輯。', 'work.empty': '沒有符合的未完成工作'
};
export const workEn: Record<keyof typeof workZh, string> = {
 'work.title': 'Work status, date workbench & in-app reminders', 'work.note': 'PV internal only. Work status and internal due dates are separate from regulatory case status and deadlines. No emails or follow-up cases are created.',
 'work.today': 'Today', 'work.week': 'This week', 'work.overdue': 'Overdue', 'work.timezone': 'Product work timezone', 'work.timezoneValue': 'Asia/Taipei', 'work.refreshOnly': 'Due reminders refresh only when this workbench is opened/refreshed; this is not background push or scheduling.',
 'work.notifications': 'In-app reminders', 'work.markRead': 'Mark read', 'work.read': 'Read', 'work.dueNotice': 'An internal work item is due or overdue.', 'work.assignedNotice': 'An internal work item has been assigned to you.',
 'work.status': 'Internal work status', 'work.statusSeparate': 'This status does not change regulatory case status, Day 0, or submission workflow.', 'work.status.todo': 'To do', 'work.status.in-progress': 'In progress', 'work.status.waiting': 'Waiting', 'work.status.completed': 'Completed', 'work.status.cancelled': 'Cancelled', 'work.cancelReason': 'Cancellation reason (required, max 500 characters)',
 'work.owner': 'Assignee', 'work.next': 'Next action', 'work.due': 'Internal work due date', 'work.items': 'Information requests', 'work.addItem': 'Add request', 'work.pending': 'Pending', 'work.received': 'Received', 'work.cancelled': 'Cancelled', 'work.contacts': 'Contact history', 'work.addContact': 'Add contact', 'work.date': 'Contact date', 'work.method': 'Method', 'work.result': 'Outcome', 'work.follow': 'Next follow-up date', 'work.phone': 'Phone', 'work.email': 'Email', 'work.visit': 'Visit', 'work.other': 'Other', 'work.unassigned': 'Unassigned', 'work.save': 'Save work', 'work.reload': 'Refresh workbench', 'work.loading': 'Loading…', 'work.saved': 'Saved',
 'work.unread': 'unread', 'work.unsaved': 'Unsaved', 'work.itemTitle': 'Request', 'work.itemStatus': 'Status', 'work.auditVersion': 'Version', 'work.auditAt': 'Time', 'work.auditActor': 'Actor', 'work.auditAction': 'Action', 'work.action.work_saved': 'Saved', 'work.action.work_completed': 'Marked complete', 'work.action.work_cancelled': 'Work cancelled', 'work.action.work_reopened': 'Reopened',
 'work.error': 'Load/save failed. Check connection, PV permission and schema. Edits are not saved.', 'work.conflict': 'Another user changed this work. Your edits are retained. Copy anything needed, refresh the latest version, then reapply changes.', 'work.invalid': 'Check status transition, cancellation reason, dates, lengths and assignee.', 'work.audit': 'Server audit trail', 'work.dirty': 'Unsaved edits: save or discard first.', 'work.empty': 'No matching active work'
};
