import { describe, it, expect } from 'vitest';
import { emptyWork, validateWork, normalizeStoredWork, transitionFor, matchesWork } from '../../services/ae/caseWorkModel.js';
import { taipeiRange, handleWork } from './work.js';
import { handleAeRequest } from './ae.js';
const request = (method = 'GET', body?: any, path = '/demo/work') => new Request(`https://example.test/api/ae-reports${path}`, { method, ...(body ? { body: JSON.stringify(body) } : {}) });
function mock(changes = 1) { const writes: any[] = []; const env = { AE_PV_EMAILS: 'bootstrap@example.test', DB: { prepare(sql: string) { let args: any[] = []; return { bind(...v: any[]) { args = v; return this; }, async first() { if (sql.includes('FROM ae_users')) return { role: 'pv' }; if (sql.includes('FROM ae_case_work')) return null; return { id: 'demo' }; }, async all() { return { results: sql.includes('FROM ae_users') ? [{ email: 'pv@example.test' }] : [] }; }, async run() { writes.push({ sql, args }); return { meta: { changes } }; } }; } } }; return { env, writes }; }
describe('work status model, compatibility and Taipei date rules', () => {
 it('defaults legacy rows to todo without inferring terminal state', () => { const work = normalizeStoredWork({ nextAction: '', workDueDate: '', items: [] }, 7); expect(work.version).toBe(7); expect(work.status).toBe('todo'); });
 it('rejects unknown lifecycle fields, invalid dates/status and bad cancellation input', () => { for (const patch of [{ actor: 'fake' }, { completedAt: 'x' }, { status: 'other' }, { workDueDate: '2026-02-30' }, { dueDate: '2026-01-01' }, { nextAction: 'x'.repeat(1001) }, { items: Array(51).fill({}) }, { contacts: Array(101).fill({}) }, { items: [{ id: 'a', title: 'item', status: 'bad' }] }, { contacts: [{ id: 'a', date: '', method: 'phone', result: 'ok', nextFollowUp: '' }] }]) expect(() => validateWork({ ...emptyWork(), ...patch })).toThrow('INVALID_WORK'); expect(() => transitionFor('todo', 'cancelled', '')).toThrow('INVALID_CANCEL_REASON'); expect(() => transitionFor('completed', 'cancelled', 'x')).toThrow('INVALID_TRANSITION'); });
 it('retains legal items and contacts and isolates internal due date from regulatory dueDate', () => { const work = { ...emptyWork(), assignee: ' PV@example.test ', nextAction: ' ask ', items: [{ id: 'i', title: 'Synthetic request', status: 'received' }], contacts: [{ id: 'c', date: '2026-09-01', method: 'email', result: 'Synthetic contact', nextFollowUp: '2026-10-01' }] }; expect(validateWork(work)).toEqual({ ...work, assignee: 'pv@example.test', nextAction: 'ask' }); expect('dueDate' in validateWork(work)).toBe(false); });
 it('allows only terminal lifecycle transitions and explicit reopen', () => { expect(transitionFor('todo', 'completed')).toBe('work_completed'); expect(transitionFor('waiting', 'cancelled', 'duplicate')).toBe('work_cancelled'); expect(transitionFor('cancelled', 'in-progress')).toBe('work_reopened'); });
 it('excludes terminal work from all active/overdue filters', () => { expect(matchesWork({ ...emptyWork(), status: 'completed', workDueDate: '2026-09-01' }, 'overdue', '', '2026-09-02')).toBe(false); expect(matchesWork({ ...emptyWork(), status: 'todo', workDueDate: '2026-09-01' }, 'overdue', '', '2026-09-02')).toBe(true); expect(matchesWork({ ...emptyWork(), assignee: 'pv@example.test' }, 'mine', 'PV@example.test', '2026-09-02')).toBe(true); expect(matchesWork(emptyWork(), 'unassigned', '', '2026-09-02')).toBe(true); });
 it('calculates Taipei Monday-through-Sunday boundaries across UTC day', () => { const r = taipeiRange(new Date('2026-09-27T16:30:00Z')); expect(r.timezone).toBe('Asia/Taipei'); expect(r.today).toBe('2026-09-28'); expect(r.weekStart).toBe('2026-09-28'); expect(r.weekEnd).toBe('2026-10-05'); });
});
describe('PV-only backend contract', () => {
 it('rejects reps before querying workbench, notifications and work', async () => { const env = { DB: { prepare() { throw Error('must not query'); } } }; for (const path of ['/demo/work','/workbench','/notifications']) expect((await handleWork(request('GET', undefined, path), env, path.split('/').filter(Boolean), 'rep', 'rep@example.test', {})).status).toBe(403); });
 it('uses server actor/time and conditional status write', async () => { const { env, writes } = mock(); const res = await handleWork(request('PUT', { ...emptyWork(), status: 'completed' }), env, ['demo','work'], 'pv', 'verified@example.test', {}); expect(res.status).toBe(200); const data = await res.json(); expect(data.work.status).toBe('completed'); expect(data.work.completedBy).toBe('verified@example.test'); expect(Date.parse(data.work.completedAt)).toBeGreaterThan(Date.parse('2026-01-01')); expect(writes[0].sql).toContain('WHERE ae_case_work.version = ?'); expect(writes[0].args).toContain('work_completed'); });
 it('rejects stale and client forged lifecycle writes', async () => { const { env } = mock(0); expect((await handleWork(request('PUT', emptyWork()), env, ['demo','work'], 'pv', 'pv@example.test', {})).status).toBe(409); const fresh = mock(); expect((await handleWork(request('PUT', { ...emptyWork(), completedAt: 'spoof' }), fresh.env, ['demo','work'], 'pv', 'pv@example.test', {})).status).toBe(400); });
 it('keeps directory minimal/no-store and rejects malformed, oversized and general-case work input before writes', async () => { const { env, writes } = mock(); const directory = await handleWork(request('GET', undefined, '/work-users'), env, ['work-users'], 'pv', 'pv@example.test', {}); expect((await directory.json()).users).toEqual(['pv@example.test', 'bootstrap@example.test']); expect(directory.headers.get('Cache-Control')).toBe('no-store'); expect((await handleWork(request('PUT', { data: 'x'.repeat(200001) }), env, ['demo','work'], 'pv', 'pv@example.test', {})).status).toBe(413); expect((await handleWork(new Request('https://example.test', { method: 'PUT', body: '{' }), env, ['demo','work'], 'pv', 'pv@example.test', {})).status).toBe(400); const req = new Request('https://example.test/api/ae-reports', { method: 'POST', body: JSON.stringify({ id: 'demo', workDueDate: '2026-09-01' }) }); const aeEnv:any = { AE_PV_EMAILS: '', DB: { prepare() { return { bind() { return this; }, async first() { return { role: 'rep' }; } }; } } }; expect((await handleAeRequest(req, aeEnv, new URL(req.url), { email: 'rep@example.test' }, {})).status).toBe(400); expect(writes).toHaveLength(0); });
});
